export const images = {
  splashBackground: require('./assets/splash-background.png'),
  logo: require('./assets/river-rock-logo.png'),
  food: {
    ribeye: require('./assets/food-grilled-ribeye.png'),
    salmon: require('./assets/food-atlantic-salmon.png'),
    chicken: require('./assets/food-chicken-supreme.png'),
    pasta: require('./assets/food-truffle-mushroom-pasta.png'),
    ribs: require('./assets/food-braised-short-ribs.png'),
    poke: require('./assets/food-pacific-poke-bowl.png'),
    caesar: require('./assets/food-caesar-salad.png'),
    mediterranean: require('./assets/food-mediterranean-bowl.png'),
    shrimp: require('./assets/food-shrimp-avocado-salad.png'),
    smokedSalmon: require('./assets/food-smoked-salmon-plate.png'),
    cheesecake: require('./assets/food-new-york-cheesecake.png'),
    lavaCake: require('./assets/food-chocolate-lava-cake.png'),
    fruit: require('./assets/food-seasonal-fruit-platter.png'),
    cappuccino: require('./assets/food-signature-cappuccino.png'),
    smoothie: require('./assets/food-tropical-smoothie.png'),
  },
  places: {
    garryPoint: require('./assets/place-garry-point-park.png'),
    westDyke: require('./assets/place-west-dyke-trail.png'),
    middleArm: require('./assets/place-middle-arm-waterfront-greenway.png'),
    stevestonWharf: require('./assets/place-steveston-fishermans-wharf.png'),
    imperialLanding: require('./assets/place-imperial-landing-park.png'),
    londonWharf: require('./assets/place-london-wharf-park.png'),
    terraNova: require('./assets/place-terra-nova-rural-park.png'),
    ionaBeach: require('./assets/place-iona-beach-regional-park.png'),
    richmondNature: require('./assets/place-richmond-nature-park.png'),
    kingGeorgeCambie: require('./assets/place-king-george-cambie-community-park.png'),
    gardenCity: require('./assets/place-garden-city-lands.png'),
    southDyke: require('./assets/place-south-dyke-trail.png'),
    cannery: require('./assets/place-gulf-of-georgia-cannery.png'),
    britannia: require('./assets/place-britannia-shipyards.png'),
    oval: require('./assets/place-richmond-olympic-oval.png'),
    stevestonVillage: require('./assets/place-steveston-village.png'),
    museum: require('./assets/place-richmond-museum.png'),
    culturalCentre: require('./assets/place-richmond-cultural-centre.png'),
  },
};
